// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package CSR_GPT_pkg;

    localparam CSR_GPT_DATA_WIDTH = 32;
    localparam CSR_GPT_MIN_ADDR_WIDTH = 7;
    localparam CSR_GPT_SIZE = 'h44;

    typedef struct {
        logic next;
    } TIM_CR1__CEN__in_t;

    typedef struct {
        logic [1:0] next;
    } TIM_CR1__CMS__in_t;

    typedef struct {
        TIM_CR1__CEN__in_t CEN;
        TIM_CR1__CMS__in_t CMS;
    } TIM_CR1__in_t;

    typedef struct {
        logic next;
    } TIM_DIER__UIE__in_t;

    typedef struct {
        logic next;
    } TIM_DIER__CC1IE__in_t;

    typedef struct {
        logic next;
    } TIM_DIER__CC2IE__in_t;

    typedef struct {
        logic next;
    } TIM_DIER__CC3IE__in_t;

    typedef struct {
        logic next;
    } TIM_DIER__CC4IE__in_t;

    typedef struct {
        logic next;
    } TIM_DIER__TIE__in_t;

    typedef struct {
        logic next;
    } TIM_DIER__UDE__in_t;

    typedef struct {
        logic next;
    } TIM_DIER__CC1DE__in_t;

    typedef struct {
        logic next;
    } TIM_DIER__CC2DE__in_t;

    typedef struct {
        logic next;
    } TIM_DIER__CC3DE__in_t;

    typedef struct {
        logic next;
    } TIM_DIER__CC4DE__in_t;

    typedef struct {
        logic next;
    } TIM_DIER__TDE__in_t;

    typedef struct {
        TIM_DIER__UIE__in_t UIE;
        TIM_DIER__CC1IE__in_t CC1IE;
        TIM_DIER__CC2IE__in_t CC2IE;
        TIM_DIER__CC3IE__in_t CC3IE;
        TIM_DIER__CC4IE__in_t CC4IE;
        TIM_DIER__TIE__in_t TIE;
        TIM_DIER__UDE__in_t UDE;
        TIM_DIER__CC1DE__in_t CC1DE;
        TIM_DIER__CC2DE__in_t CC2DE;
        TIM_DIER__CC3DE__in_t CC3DE;
        TIM_DIER__CC4DE__in_t CC4DE;
        TIM_DIER__TDE__in_t TDE;
    } TIM_DIER__in_t;

    typedef struct {
        logic next;
    } TIM_SR__UIF__in_t;

    typedef struct {
        logic next;
    } TIM_SR__CC1IF__in_t;

    typedef struct {
        logic next;
    } TIM_SR__CC2IF__in_t;

    typedef struct {
        logic next;
    } TIM_SR__CC3IF__in_t;

    typedef struct {
        logic next;
    } TIM_SR__CC4IF__in_t;

    typedef struct {
        logic next;
    } TIM_SR__TIF__in_t;

    typedef struct {
        logic next;
    } TIM_SR__CC1OF__in_t;

    typedef struct {
        logic next;
    } TIM_SR__CC2OF__in_t;

    typedef struct {
        logic next;
    } TIM_SR__CC3OF__in_t;

    typedef struct {
        logic next;
    } TIM_SR__CC4OF__in_t;

    typedef struct {
        TIM_SR__UIF__in_t UIF;
        TIM_SR__CC1IF__in_t CC1IF;
        TIM_SR__CC2IF__in_t CC2IF;
        TIM_SR__CC3IF__in_t CC3IF;
        TIM_SR__CC4IF__in_t CC4IF;
        TIM_SR__TIF__in_t TIF;
        TIM_SR__CC1OF__in_t CC1OF;
        TIM_SR__CC2OF__in_t CC2OF;
        TIM_SR__CC3OF__in_t CC3OF;
        TIM_SR__CC4OF__in_t CC4OF;
    } TIM_SR__in_t;

    typedef struct {
        logic next;
    } TIM_EGR__UG__in_t;

    typedef struct {
        logic next;
    } TIM_EGR__CC1G__in_t;

    typedef struct {
        logic next;
    } TIM_EGR__CC2G__in_t;

    typedef struct {
        logic next;
    } TIM_EGR__CC3G__in_t;

    typedef struct {
        logic next;
    } TIM_EGR__CC4G__in_t;

    typedef struct {
        logic next;
    } TIM_EGR__TG__in_t;

    typedef struct {
        TIM_EGR__UG__in_t UG;
        TIM_EGR__CC1G__in_t CC1G;
        TIM_EGR__CC2G__in_t CC2G;
        TIM_EGR__CC3G__in_t CC3G;
        TIM_EGR__CC4G__in_t CC4G;
        TIM_EGR__TG__in_t TG;
    } TIM_EGR__in_t;

    typedef struct {
        logic next;
    } TIM_CCER__CC1E__in_t;

    typedef struct {
        logic next;
    } TIM_CCER__CC1P__in_t;

    typedef struct {
        logic next;
    } TIM_CCER__CC1NP__in_t;

    typedef struct {
        logic next;
    } TIM_CCER__CC2E__in_t;

    typedef struct {
        logic next;
    } TIM_CCER__CC2P__in_t;

    typedef struct {
        logic next;
    } TIM_CCER__CC2NP__in_t;

    typedef struct {
        logic next;
    } TIM_CCER__CC3E__in_t;

    typedef struct {
        logic next;
    } TIM_CCER__CC3P__in_t;

    typedef struct {
        logic next;
    } TIM_CCER__CC3NP__in_t;

    typedef struct {
        logic next;
    } TIM_CCER__CC4E__in_t;

    typedef struct {
        logic next;
    } TIM_CCER__CC4P__in_t;

    typedef struct {
        logic next;
    } TIM_CCER__CC4NP__in_t;

    typedef struct {
        TIM_CCER__CC1E__in_t CC1E;
        TIM_CCER__CC1P__in_t CC1P;
        TIM_CCER__CC1NP__in_t CC1NP;
        TIM_CCER__CC2E__in_t CC2E;
        TIM_CCER__CC2P__in_t CC2P;
        TIM_CCER__CC2NP__in_t CC2NP;
        TIM_CCER__CC3E__in_t CC3E;
        TIM_CCER__CC3P__in_t CC3P;
        TIM_CCER__CC3NP__in_t CC3NP;
        TIM_CCER__CC4E__in_t CC4E;
        TIM_CCER__CC4P__in_t CC4P;
        TIM_CCER__CC4NP__in_t CC4NP;
    } TIM_CCER__in_t;

    typedef struct {
        logic [31:0] next;
    } TIM_CNT__CNT__in_t;

    typedef struct {
        TIM_CNT__CNT__in_t CNT;
    } TIM_CNT__in_t;

    typedef struct {
        logic [31:0] next;
    } TIM_PSC__PSC__in_t;

    typedef struct {
        TIM_PSC__PSC__in_t PSC;
    } TIM_PSC__in_t;

    typedef struct {
        logic [31:0] next;
    } TIM_ARR__ARR__in_t;

    typedef struct {
        TIM_ARR__ARR__in_t ARR;
    } TIM_ARR__in_t;

    typedef struct {
        logic [31:0] next;
    } TIM_CCR__CCR__in_t;

    typedef struct {
        TIM_CCR__CCR__in_t CCR;
    } TIM_CCR__in_t;

    typedef struct {
        logic [1:0] next;
    } TIM_CCMR__CC1S__in_t;

    typedef struct {
        logic next;
    } TIM_CCMR__OC1FE_IC1PSC0__in_t;

    typedef struct {
        logic next;
    } TIM_CCMR__OC1PE_IC1PSC1__in_t;

    typedef struct {
        logic [2:0] next;
    } TIM_CCMR__OC1M_IC1F__in_t;

    typedef struct {
        logic next;
    } TIM_CCMR__OC1CE_IC1F3__in_t;

    typedef struct {
        logic [1:0] next;
    } TIM_CCMR__CC2S__in_t;

    typedef struct {
        logic next;
    } TIM_CCMR__OC2FE_IC2PSC0__in_t;

    typedef struct {
        logic next;
    } TIM_CCMR__OC2PE_IC2PSC1__in_t;

    typedef struct {
        logic [2:0] next;
    } TIM_CCMR__OC2M_IC2F__in_t;

    typedef struct {
        logic next;
    } TIM_CCMR__OC2CE_IC2F3__in_t;

    typedef struct {
        TIM_CCMR__CC1S__in_t CC1S;
        TIM_CCMR__OC1FE_IC1PSC0__in_t OC1FE_IC1PSC0;
        TIM_CCMR__OC1PE_IC1PSC1__in_t OC1PE_IC1PSC1;
        TIM_CCMR__OC1M_IC1F__in_t OC1M_IC1F;
        TIM_CCMR__OC1CE_IC1F3__in_t OC1CE_IC1F3;
        TIM_CCMR__CC2S__in_t CC2S;
        TIM_CCMR__OC2FE_IC2PSC0__in_t OC2FE_IC2PSC0;
        TIM_CCMR__OC2PE_IC2PSC1__in_t OC2PE_IC2PSC1;
        TIM_CCMR__OC2M_IC2F__in_t OC2M_IC2F;
        TIM_CCMR__OC2CE_IC2F3__in_t OC2CE_IC2F3;
    } TIM_CCMR__in_t;

    typedef struct {
        TIM_CR1__in_t TIM_CR1;
        TIM_DIER__in_t TIM_DIER;
        TIM_SR__in_t TIM_SR;
        TIM_EGR__in_t TIM_EGR;
        TIM_CCER__in_t TIM_CCER;
        TIM_CNT__in_t TIM_CNT;
        TIM_PSC__in_t TIM_PSC;
        TIM_ARR__in_t TIM_ARR;
        TIM_CCR__in_t TIM_CCR1;
        TIM_CCR__in_t TIM_CCR2;
        TIM_CCR__in_t TIM_CCR3;
        TIM_CCR__in_t TIM_CCR4;
        TIM_CCMR__in_t TIM_CCMR1;
        TIM_CCMR__in_t TIM_CCMR2;
    } CSR_GPT__in_t;

    typedef struct {
        logic value;
    } TIM_CR1__CEN__out_t;

    typedef struct {
        logic value;
    } TIM_CR1__URS__out_t;

    typedef struct {
        logic value;
    } TIM_CR1__OPM__out_t;

    typedef struct {
        logic value;
    } TIM_CR1__DIR__out_t;

    typedef struct {
        logic [1:0] value;
    } TIM_CR1__CMS__out_t;

    typedef struct {
        logic value;
    } TIM_CR1__APRE__out_t;

    typedef struct {
        logic [1:0] value;
    } TIM_CR1__CKD__out_t;

    typedef struct {
        logic [5:0] value;
    } TIM_CR1__RESERVED_15_10__out_t;

    typedef struct {
        TIM_CR1__CEN__out_t CEN;
        TIM_CR1__URS__out_t URS;
        TIM_CR1__OPM__out_t OPM;
        TIM_CR1__DIR__out_t DIR;
        TIM_CR1__CMS__out_t CMS;
        TIM_CR1__APRE__out_t APRE;
        TIM_CR1__CKD__out_t CKD;
        TIM_CR1__RESERVED_15_10__out_t RESERVED_15_10;
    } TIM_CR1__out_t;

    typedef struct {
        logic [2:0] value;
    } TIM_CR2__RESERVED_2_0__out_t;

    typedef struct {
        logic value;
    } TIM_CR2__CCDS__out_t;

    typedef struct {
        logic [2:0] value;
    } TIM_CR2__MMS__out_t;

    typedef struct {
        logic value;
    } TIM_CR2__TI1S__out_t;

    typedef struct {
        logic [7:0] value;
    } TIM_CR2__RESERVED_15_8__out_t;

    typedef struct {
        TIM_CR2__RESERVED_2_0__out_t RESERVED_2_0;
        TIM_CR2__CCDS__out_t CCDS;
        TIM_CR2__MMS__out_t MMS;
        TIM_CR2__TI1S__out_t TI1S;
        TIM_CR2__RESERVED_15_8__out_t RESERVED_15_8;
    } TIM_CR2__out_t;

    typedef struct {
        logic [2:0] value;
    } TIM_SMCR__SMS__out_t;

    typedef struct {
        logic value;
    } TIM_SMCR__RESERVED__out_t;

    typedef struct {
        logic [2:0] value;
    } TIM_SMCR__TS__out_t;

    typedef struct {
        logic value;
    } TIM_SMCR__MSM__out_t;

    typedef struct {
        logic [3:0] value;
    } TIM_SMCR__ETF__out_t;

    typedef struct {
        logic [1:0] value;
    } TIM_SMCR__ETPS__out_t;

    typedef struct {
        logic value;
    } TIM_SMCR__ECE__out_t;

    typedef struct {
        logic value;
    } TIM_SMCR__ETP__out_t;

    typedef struct {
        TIM_SMCR__SMS__out_t SMS;
        TIM_SMCR__RESERVED__out_t RESERVED;
        TIM_SMCR__TS__out_t TS;
        TIM_SMCR__MSM__out_t MSM;
        TIM_SMCR__ETF__out_t ETF;
        TIM_SMCR__ETPS__out_t ETPS;
        TIM_SMCR__ECE__out_t ECE;
        TIM_SMCR__ETP__out_t ETP;
    } TIM_SMCR__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__UIE__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__CC1IE__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__CC2IE__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__CC3IE__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__CC4IE__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__reserved_5__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__TIE__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__reserved_7__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__UDE__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__CC1DE__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__CC2DE__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__CC3DE__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__CC4DE__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__reserved_13__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__TDE__out_t;

    typedef struct {
        logic value;
    } TIM_DIER__reserved_15__out_t;

    typedef struct {
        TIM_DIER__UIE__out_t UIE;
        TIM_DIER__CC1IE__out_t CC1IE;
        TIM_DIER__CC2IE__out_t CC2IE;
        TIM_DIER__CC3IE__out_t CC3IE;
        TIM_DIER__CC4IE__out_t CC4IE;
        TIM_DIER__reserved_5__out_t reserved_5;
        TIM_DIER__TIE__out_t TIE;
        TIM_DIER__reserved_7__out_t reserved_7;
        TIM_DIER__UDE__out_t UDE;
        TIM_DIER__CC1DE__out_t CC1DE;
        TIM_DIER__CC2DE__out_t CC2DE;
        TIM_DIER__CC3DE__out_t CC3DE;
        TIM_DIER__CC4DE__out_t CC4DE;
        TIM_DIER__reserved_13__out_t reserved_13;
        TIM_DIER__TDE__out_t TDE;
        TIM_DIER__reserved_15__out_t reserved_15;
    } TIM_DIER__out_t;

    typedef struct {
        logic value;
    } TIM_SR__UIF__out_t;

    typedef struct {
        logic value;
    } TIM_SR__CC1IF__out_t;

    typedef struct {
        logic value;
    } TIM_SR__CC2IF__out_t;

    typedef struct {
        logic value;
    } TIM_SR__CC3IF__out_t;

    typedef struct {
        logic value;
    } TIM_SR__CC4IF__out_t;

    typedef struct {
        logic value;
    } TIM_SR__reserved_5__out_t;

    typedef struct {
        logic value;
    } TIM_SR__TIF__out_t;

    typedef struct {
        logic [1:0] value;
    } TIM_SR__reserved_8_7__out_t;

    typedef struct {
        logic value;
    } TIM_SR__CC1OF__out_t;

    typedef struct {
        logic value;
    } TIM_SR__CC2OF__out_t;

    typedef struct {
        logic value;
    } TIM_SR__CC3OF__out_t;

    typedef struct {
        logic value;
    } TIM_SR__CC4OF__out_t;

    typedef struct {
        logic [2:0] value;
    } TIM_SR__reserved_15_13__out_t;

    typedef struct {
        TIM_SR__UIF__out_t UIF;
        TIM_SR__CC1IF__out_t CC1IF;
        TIM_SR__CC2IF__out_t CC2IF;
        TIM_SR__CC3IF__out_t CC3IF;
        TIM_SR__CC4IF__out_t CC4IF;
        TIM_SR__reserved_5__out_t reserved_5;
        TIM_SR__TIF__out_t TIF;
        TIM_SR__reserved_8_7__out_t reserved_8_7;
        TIM_SR__CC1OF__out_t CC1OF;
        TIM_SR__CC2OF__out_t CC2OF;
        TIM_SR__CC3OF__out_t CC3OF;
        TIM_SR__CC4OF__out_t CC4OF;
        TIM_SR__reserved_15_13__out_t reserved_15_13;
    } TIM_SR__out_t;

    typedef struct {
        logic value;
    } TIM_EGR__UG__out_t;

    typedef struct {
        logic value;
    } TIM_EGR__CC1G__out_t;

    typedef struct {
        logic value;
    } TIM_EGR__CC2G__out_t;

    typedef struct {
        logic value;
    } TIM_EGR__CC3G__out_t;

    typedef struct {
        logic value;
    } TIM_EGR__CC4G__out_t;

    typedef struct {
        logic value;
    } TIM_EGR__reserved_5__out_t;

    typedef struct {
        logic value;
    } TIM_EGR__TG__out_t;

    typedef struct {
        logic [8:0] value;
    } TIM_EGR__reserved_15_7__out_t;

    typedef struct {
        TIM_EGR__UG__out_t UG;
        TIM_EGR__CC1G__out_t CC1G;
        TIM_EGR__CC2G__out_t CC2G;
        TIM_EGR__CC3G__out_t CC3G;
        TIM_EGR__CC4G__out_t CC4G;
        TIM_EGR__reserved_5__out_t reserved_5;
        TIM_EGR__TG__out_t TG;
        TIM_EGR__reserved_15_7__out_t reserved_15_7;
    } TIM_EGR__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__CC1E__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__CC1P__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__reserved_2__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__CC1NP__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__CC2E__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__CC2P__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__reserved_6__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__CC2NP__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__CC3E__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__CC3P__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__reserved_10__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__CC3NP__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__CC4E__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__CC4P__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__reserved_14__out_t;

    typedef struct {
        logic value;
    } TIM_CCER__CC4NP__out_t;

    typedef struct {
        TIM_CCER__CC1E__out_t CC1E;
        TIM_CCER__CC1P__out_t CC1P;
        TIM_CCER__reserved_2__out_t reserved_2;
        TIM_CCER__CC1NP__out_t CC1NP;
        TIM_CCER__CC2E__out_t CC2E;
        TIM_CCER__CC2P__out_t CC2P;
        TIM_CCER__reserved_6__out_t reserved_6;
        TIM_CCER__CC2NP__out_t CC2NP;
        TIM_CCER__CC3E__out_t CC3E;
        TIM_CCER__CC3P__out_t CC3P;
        TIM_CCER__reserved_10__out_t reserved_10;
        TIM_CCER__CC3NP__out_t CC3NP;
        TIM_CCER__CC4E__out_t CC4E;
        TIM_CCER__CC4P__out_t CC4P;
        TIM_CCER__reserved_14__out_t reserved_14;
        TIM_CCER__CC4NP__out_t CC4NP;
    } TIM_CCER__out_t;

    typedef struct {
        logic [31:0] value;
    } TIM_CNT__CNT__out_t;

    typedef struct {
        TIM_CNT__CNT__out_t CNT;
    } TIM_CNT__out_t;

    typedef struct {
        logic [31:0] value;
    } TIM_PSC__PSC__out_t;

    typedef struct {
        TIM_PSC__PSC__out_t PSC;
    } TIM_PSC__out_t;

    typedef struct {
        logic [31:0] value;
    } TIM_ARR__ARR__out_t;

    typedef struct {
        TIM_ARR__ARR__out_t ARR;
    } TIM_ARR__out_t;

    typedef struct {
        logic [31:0] value;
    } TIM_CCR__CCR__out_t;

    typedef struct {
        TIM_CCR__CCR__out_t CCR;
    } TIM_CCR__out_t;

    typedef struct {
        logic [1:0] value;
    } TIM_CCMR__CC1S__out_t;

    typedef struct {
        logic value;
    } TIM_CCMR__OC1FE_IC1PSC0__out_t;

    typedef struct {
        logic value;
    } TIM_CCMR__OC1PE_IC1PSC1__out_t;

    typedef struct {
        logic [2:0] value;
    } TIM_CCMR__OC1M_IC1F__out_t;

    typedef struct {
        logic value;
    } TIM_CCMR__OC1CE_IC1F3__out_t;

    typedef struct {
        logic [1:0] value;
    } TIM_CCMR__CC2S__out_t;

    typedef struct {
        logic value;
    } TIM_CCMR__OC2FE_IC2PSC0__out_t;

    typedef struct {
        logic value;
    } TIM_CCMR__OC2PE_IC2PSC1__out_t;

    typedef struct {
        logic [2:0] value;
    } TIM_CCMR__OC2M_IC2F__out_t;

    typedef struct {
        logic value;
    } TIM_CCMR__OC2CE_IC2F3__out_t;

    typedef struct {
        TIM_CCMR__CC1S__out_t CC1S;
        TIM_CCMR__OC1FE_IC1PSC0__out_t OC1FE_IC1PSC0;
        TIM_CCMR__OC1PE_IC1PSC1__out_t OC1PE_IC1PSC1;
        TIM_CCMR__OC1M_IC1F__out_t OC1M_IC1F;
        TIM_CCMR__OC1CE_IC1F3__out_t OC1CE_IC1F3;
        TIM_CCMR__CC2S__out_t CC2S;
        TIM_CCMR__OC2FE_IC2PSC0__out_t OC2FE_IC2PSC0;
        TIM_CCMR__OC2PE_IC2PSC1__out_t OC2PE_IC2PSC1;
        TIM_CCMR__OC2M_IC2F__out_t OC2M_IC2F;
        TIM_CCMR__OC2CE_IC2F3__out_t OC2CE_IC2F3;
    } TIM_CCMR__out_t;

    typedef struct {
        TIM_CR1__out_t TIM_CR1;
        TIM_CR2__out_t TIM_CR2;
        TIM_SMCR__out_t TIM_SMCR;
        TIM_DIER__out_t TIM_DIER;
        TIM_SR__out_t TIM_SR;
        TIM_EGR__out_t TIM_EGR;
        TIM_CCER__out_t TIM_CCER;
        TIM_CNT__out_t TIM_CNT;
        TIM_PSC__out_t TIM_PSC;
        TIM_ARR__out_t TIM_ARR;
        TIM_CCR__out_t TIM_CCR1;
        TIM_CCR__out_t TIM_CCR2;
        TIM_CCR__out_t TIM_CCR3;
        TIM_CCR__out_t TIM_CCR4;
        TIM_CCMR__out_t TIM_CCMR1;
        TIM_CCMR__out_t TIM_CCMR2;
    } CSR_GPT__out_t;
endpackage
